{% set name = "openpnm" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 470bd3969d8af748127048ccfd3fda4c85a2b3306464373923b9455d56c10d06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-image
    - pandas
    - numba
    - networkx
    - h5py
    - jsonschema
    - terminaltables
    - unyt
    - gitpython
    - flatdict
    - transforms3d
    - sympy
    - docrep

test:
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://openpnm.readthedocs.io/en/master/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
