{% set name = "openpnm" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 066baabf84bcb7b10a8bb8672c8468ad525bec946db3d311e6a936d262dd4ecc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - chemicals
    - docrep >=0.3
    - h5py
    - jsonschema
    - matplotlib-base
    - networkx
    - numba
    - numpy
    - pandas
    - pyamg
    - pypardiso
    - rich
    - scikit-image
    - scipy
    - sympy
    - thermo
    - tqdm
    - transforms3d

test:
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://pmeal.github.io/OpenPNM/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
