{% set name = "openpnm" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29548f8cf89433703f0831d122b86d6bd630f911726cd1de461235610d279c1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9                           # [build_platform != target_platform]
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - chemicals
    - docrep >=0.3
    - h5py
    - jsonschema
    - matplotlib-base
    - networkx
    - numba
    - numpy
    - pandas
    - pyamg
    - pypardiso
    - rich
    - scikit-image
    - scipy
    - sympy
    - thermo
    - tqdm
    - transforms3d
    - setuptools

test:
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://pmeal.github.io/OpenPNM/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
