{% set name = "openpnm" %}
{% set version = "3.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c437aa6890c1c4da589589ae1cd4e9563a3c018768898203c367383611f7dadf

build:
  number: 4
  noarch: python
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - chemicals
    - docrep >=0.3
    - h5py
    - jsonschema
    - matplotlib-base
    - networkx
    - numba
    - numpy
    - pandas
    - pyamg
    - rich
    - scikit-image
    - scipy
    - sympy
    - thermo
    - tqdm
    - transforms3d
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://pmeal.github.io/OpenPNM/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
