{% set name = "openpnm" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ec64fbb88cbe02cb73b61ad457a6db60bfe9c2810b6ec4465755e483006a4ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-image
    - pandas
    - numba
    - networkx
    - h5py
    - jsonschema
    - terminaltables
    - unyt
    - gitpython
    - flatdict
    - transforms3d
    - sympy
    - pardiso4py
    - docrep ==0.2.7
    - json_tricks

test:
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://openpnm.readthedocs.io/en/dev/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
