{% set name = "openpnm" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7171ef432a0383e4f243ff169d52a983b9b95f10a6b41ca4e7b648f2b5928eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - chemicals
    - docrep >=0.3
    - flatdict
    - gitpython
    - h5py
    - ipython
    - jsonschema
    - json_tricks
    - matplotlib-base
    - networkx
    - numba
    - numpy
    - pandas
    - pypardiso
    - scikit-image
    - scipy
    - sympy
    - terminaltables
    - tqdm
    - transforms3d

test:
  imports:
    - openpnm

about:
  home: https://github.com/PMEAL/OpenPNM/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for performing pore network modeling of porous media
  description: OpenPNM is a comprehensive framework for performing pore network simulations of porous materials.

  doc_url: https://pmeal.github.io/OpenPNM/
  dev_url: https://github.com/PMEAL/OpenPNM/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
